# Generated by Django 5.0.7 on 2024-08-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='links',
            new_name='social_links',
        ),
    ]
