# Generated by Django 5.0.7 on 2024-08-02 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='public',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='public',
            old_name='desc',
            new_name='teg',
        ),
        migrations.AddField(
            model_name='comment',
            name='public',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.public'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='public',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='public',
            name='title',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
