# Generated by Django 5.0.7 on 2024-08-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_comment_comment_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='category',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('public', models.ManyToManyField(to='main.public')),
            ],
        ),
    ]
