# Generated by Django 5.0.7 on 2024-08-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_public_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='public',
        ),
        migrations.AddField(
            model_name='public',
            name='public',
            field=models.ManyToManyField(to='main.category'),
        ),
    ]
