# Generated by Django 5.0.7 on 2024-08-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_public_category_public_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='category',
        ),
        migrations.AddField(
            model_name='public',
            name='category',
            field=models.ManyToManyField(to='main.category'),
        ),
    ]
