# Generated by Django 5.0.7 on 2024-08-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_category_public_public_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='public',
            field=models.ManyToManyField(related_name='publics', to='main.category'),
        ),
    ]
