# Generated by Django 5.0.7 on 2024-08-09 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_public_category_public_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='category',
        ),
        migrations.AddField(
            model_name='public',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
            preserve_default=False,
        ),
    ]
