# Generated by Django 5.0.7 on 2024-08-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_public_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='public',
            old_name='public',
            new_name='category',
        ),
    ]
